from talon.voice import Key

emoji = {
    'thumbs up': ':+1:',
    'okay hand': ':ok_hand:',
    'arm muscle': ':muscle:',
    'happy smiley': ':smiley:',
    'smiley': ':slightly_smiling_face:',
    'laugh out loud': ':joy:',
    'thinking face': ':thinking_face:',
    'sweat smile': ':sweat_smile:',
    'checkmark': ':white_check_mark:',
    'blush': ':blush:',
    'blush': ':blush:',
    'comment emoji': ':comment:',
    'speech balloon': ':speech_balloon:',
    'star emoji': ':star:',
    'merged emoji': ':merged:',
    'reading emoji': ':reading:',
    'celebrate': ':tada:',
    'champagne': ':champagne:',
    'upvote': ':upvote:',
    'praying hands': ':pray:',
    'read heart ': ':heart:',
    'mind blown': [':mindblown1::mindblown2:', Key('shift-enter'), ':mindblown3::mindblown4:'],
    'amazed': [':mindblown1::mindblown2:', Key('shift-enter'), ':mindblown3::mindblown4:'],

    '(highlight command | insert command)': ['``', Key('left')],
    'clear text': [Key('cmd-a'), Key('backspace')],
}
